### PR TITLE
Add Home-ota administration/management tool

### PR DESCRIPTION
**Pull request by fvdpol**
Add JP Mens'  Homie-ota tool.  

It provides an OTA server for Homie devices as well as a simple inventory which can be useful to keep track of Homie devices. Homie-ota also enables you to trigger an OTA update (over MQTT, using the Homie convention) from within its inventory. New firmware can be uploaded to homie-ota which detects firmware name (fwname) and version (fwversion) from the uploaded binary blob.

### CODE REVIEW

**Comment by davidgraeff** [comment]
Perfect. I have skimmed through your sources and noticed that you use the `$implementation/ota/firmware` topic.

This is not defined on Homie 3.0+.
You are basically doing Homie 3.0 + "OTA Extension 1.0".

That is entirely OK, but it would be super helpful if you could work with firmware implementors together to come up with a name for that extension and a specification document. We will link that from the Homie main specification.

For now I like you to say in the version column "3.0 + Custom OTA". Thanks :)

**Review by davidgraeff — APPROVED** [review]

**Comment by fvdpol** [comment]
Thanks for your feedback @davidgraeff.  I updated the version as requested and improved the implementation note for this admin tool to make the intended use/purpose more clear.

Given the primary objective of @jpmens' homie-ota to manage the firmware updates for homie-esp8266 devices this OTA server focusses on the Homie 2.0 protocol since that is still the latest released version for esp8266.   

Happy to work to both Homie and homie-ota team's to push this forward :-)

**Comment by davidgraeff** [comment]
> still the latest released version for esp8266.

Unfortunately yes. Because the main author disappeared and merging the 3.0 version is now much more difficult. But I still have hope for the next weeks for this to happen.

**Comment by marvinroger** [comment]
FYI, I gave some long time contributors full admin access to the `homieiot` organization. So, the fact that I am "disappearing" (due to personal reasons) somehow should not be a problem anymore. 😉

**Comment by marvinroger** [comment]
@davidgraeff being one of them!

**Pull request merged**
