### PR TITLE
Added FlutterHomie to Administration devices

### PR DESCRIPTION
**Pull request by Clon1998**
Added my FlutterHomie project that I started to learn and play around with Flutter.

### CODE REVIEW

**Comment by davidgraeff** [comment]
Thanks for the submission. I'd say we add your project, as soon as it is reaches a state that you wouldn't consider a "learning experience" anymore. Please also add a LICENSE file to your repository. We do not list unlicensed code :)

**Comment by Clon1998** [comment]
Just added the License.
But I am not really sure when I will reach this point.
Currently, it compiles and is usable but it does not provide full connection error handling.
I just added some Screenshots to the Readme as well.

**Comment by davidgraeff** [comment]
I have checked again, and at least you seem to maintain the repo. Adding your contribution to the Homie project so that others can easily find it. Thanks

**Comment by Clon1998** [comment]
Thanks alot

**Pull request merged**
